-- Shipment Tracker Database Schema
-- Execute this script to create all tables

-- Branch table
CREATE TABLE Branch (
    Id BIGINT IDENTITY PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL UNIQUE,
    Address NVARCHAR(200) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);

-- Role table
CREATE TABLE Role (
    Id BIGINT IDENTITY PRIMARY KEY,
    Name NVARCHAR(50) NOT NULL UNIQUE,
    RoleType TINYINT NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);

-- User table
CREATE TABLE [User] (
    Id BIGINT IDENTITY PRIMARY KEY,
    UserName NVARCHAR(50) NOT NULL UNIQUE,
    Email NVARCHAR(100) NOT NULL UNIQUE,
    PasswordHash VARBINARY(256) NOT NULL,
    DisplayName NVARCHAR(100) NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    EmailVerified BIT NOT NULL DEFAULT 0,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);

-- UserRole junction table
CREATE TABLE UserRole (
    UserId BIGINT NOT NULL,
    RoleId BIGINT NOT NULL,
    PRIMARY KEY (UserId, RoleId),
    FOREIGN KEY (UserId) REFERENCES [User](Id) ON DELETE CASCADE,
    FOREIGN KEY (RoleId) REFERENCES Role(Id) ON DELETE CASCADE
);

-- RefreshToken table
CREATE TABLE RefreshToken (
    Id BIGINT IDENTITY PRIMARY KEY,
    Token NVARCHAR(500) NOT NULL UNIQUE,
    UserId BIGINT NOT NULL,
    ExpiresAt DATETIME2 NOT NULL,
    IsRevoked BIT NOT NULL DEFAULT 0,
    RevokedAt DATETIME2 NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    FOREIGN KEY (UserId) REFERENCES [User](Id) ON DELETE CASCADE
);

-- EmailVerificationToken table
CREATE TABLE EmailVerificationToken (
    Id BIGINT IDENTITY PRIMARY KEY,
    Token NVARCHAR(500) NOT NULL UNIQUE,
    UserId BIGINT NOT NULL,
    ExpiresAt DATETIME2 NOT NULL,
    IsUsed BIT NOT NULL DEFAULT 0,
    UsedAt DATETIME2 NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    FOREIGN KEY (UserId) REFERENCES [User](Id) ON DELETE CASCADE
);

-- PasswordResetToken table
CREATE TABLE PasswordResetToken (
    Id BIGINT IDENTITY PRIMARY KEY,
    Token NVARCHAR(500) NOT NULL UNIQUE,
    UserId BIGINT NOT NULL,
    ExpiresAt DATETIME2 NOT NULL,
    IsUsed BIT NOT NULL DEFAULT 0,
    UsedAt DATETIME2 NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    FOREIGN KEY (UserId) REFERENCES [User](Id) ON DELETE CASCADE
);

-- Client table
CREATE TABLE Client (
    Id BIGINT IDENTITY PRIMARY KEY,
    UserId BIGINT NOT NULL UNIQUE,
    PhoneNumber NVARCHAR(20) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    FOREIGN KEY (UserId) REFERENCES [User](Id) ON DELETE CASCADE
);

-- Warehouse table
CREATE TABLE Warehouse (
    Id BIGINT IDENTITY PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Address NVARCHAR(200) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);

-- Port table
CREATE TABLE Port (
    Id BIGINT IDENTITY PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    Address NVARCHAR(200) NOT NULL,
    Country NVARCHAR(100) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);

-- Carrier table
CREATE TABLE Carrier (
    Id BIGINT IDENTITY PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL,
    ContactInfo NVARCHAR(200) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);

-- Batch table
CREATE TABLE Batch (
    Id BIGINT IDENTITY PRIMARY KEY,
    BranchId BIGINT NOT NULL,
    Name NVARCHAR(50) NULL,
    Status TINYINT NOT NULL DEFAULT 0,
    ShipmentCount INT NOT NULL DEFAULT 0,
    TotalWeight DECIMAL(10,2) NOT NULL DEFAULT 0,
    ThresholdCount INT NOT NULL DEFAULT 0,
    ThresholdWeight DECIMAL(10,2) NOT NULL DEFAULT 0,
    WarehouseId BIGINT NULL,
    SourcePortId BIGINT NULL,
    DestinationPortId BIGINT NULL,
    CarrierAssignedAt DATETIME2 NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    FOREIGN KEY (BranchId) REFERENCES Branch(Id),
    FOREIGN KEY (WarehouseId) REFERENCES Warehouse(Id),
    FOREIGN KEY (SourcePortId) REFERENCES Port(Id),
    FOREIGN KEY (DestinationPortId) REFERENCES Port(Id)
);

-- Shipment table
CREATE TABLE Shipment (
    Id BIGINT IDENTITY PRIMARY KEY,
    ClientId BIGINT NOT NULL,
    BatchId BIGINT NULL,
    Status TINYINT NOT NULL DEFAULT 0,
    Weight DECIMAL(10,2) NOT NULL,
    Volume DECIMAL(10,2) NULL,
    PickupAddress NVARCHAR(200) NULL,
    DeliveryAddress NVARCHAR(200) NOT NULL,
    CarrierId BIGINT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    FOREIGN KEY (ClientId) REFERENCES Client(Id),
    FOREIGN KEY (BatchId) REFERENCES Batch(Id),
    FOREIGN KEY (CarrierId) REFERENCES Carrier(Id)
);

-- ShipmentEvent table
CREATE TABLE ShipmentEvent (
    Id BIGINT IDENTITY PRIMARY KEY,
    ShipmentId BIGINT NOT NULL,
    EventType NVARCHAR(50) NOT NULL,
    ActorUserId BIGINT NULL,
    Location NVARCHAR(100) NULL,
    Message NVARCHAR(200) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    FOREIGN KEY (ShipmentId) REFERENCES Shipment(Id),
    FOREIGN KEY (ActorUserId) REFERENCES [User](Id)
);

-- Announcement table
CREATE TABLE Announcement (
    Id BIGINT IDENTITY PRIMARY KEY,
    Title NVARCHAR(100) NOT NULL,
    Content NVARCHAR(MAX) NOT NULL,
    StartDate DATETIME2 NOT NULL,
    EndDate DATETIME2 NOT NULL,
    CreatedByUserId BIGINT NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    FOREIGN KEY (CreatedByUserId) REFERENCES [User](Id)
);

-- AnnouncementTarget table
CREATE TABLE AnnouncementTarget (
    Id BIGINT IDENTITY PRIMARY KEY,
    AnnouncementId BIGINT NOT NULL,
    BranchId BIGINT NULL,
    ClientId BIGINT NULL,
    Tag NVARCHAR(50) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    UpdatedAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    FOREIGN KEY (AnnouncementId) REFERENCES Announcement(Id),
    FOREIGN KEY (BranchId) REFERENCES Branch(Id),
    FOREIGN KEY (ClientId) REFERENCES Client(Id)
);

-- AuditHeader table
CREATE TABLE AuditHeader (
    Id BIGINT IDENTITY PRIMARY KEY,
    TableName NVARCHAR(128) NOT NULL,
    RowKey NVARCHAR(128) NOT NULL,
    Operation NVARCHAR(20) NOT NULL,
    UserId BIGINT NULL,
    RecordDate DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    ActualDate DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    FOREIGN KEY (UserId) REFERENCES [User](Id)
);

-- AuditDetail table
CREATE TABLE AuditDetail (
    Id BIGINT IDENTITY PRIMARY KEY,
    AuditHeaderId BIGINT NOT NULL,
    ColumnName NVARCHAR(128) NOT NULL,
    OldValue NVARCHAR(MAX) NULL,
    NewValue NVARCHAR(MAX) NULL,
    FOREIGN KEY (AuditHeaderId) REFERENCES AuditHeader(Id) ON DELETE CASCADE
);

-- OutboxEvent table
CREATE TABLE OutboxEvent (
    Id BIGINT IDENTITY PRIMARY KEY,
    EventType NVARCHAR(100) NOT NULL,
    Payload NVARCHAR(MAX) NOT NULL,
    OccurredAt DATETIME2 NOT NULL DEFAULT SYSDATETIME(),
    ProcessedAt DATETIME2 NULL
);
